### ISSUE TITLE
failures deploying ethical hacker docker compose from `start_app` script - `chown: /var/lib/postgresql/data: Permission denied`

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [theowni/Damn-Vulnerable-RESTaurant-API-Game#2]
howdy!

```shell
➜  Damn-Vulnerable-RESTaurant-API-Game git:(main) ✗ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.3.1 (23D60)
      Kernel Version: Darwin 23.3.0
```

**note:** using `colima` ([Mac OS container runtime](https://github.com/abiosoft/colima)) instead of Docker desktop, follow the [instructions](https://github.com/theowni/Damn-Vulnerable-RESTaurant-API-Game?tab=readme-ov-file#running-the-application---ethical-hackers-approach) "Running the Application - Ethical Hackers Approach"

```shell
➜  Damn-Vulnerable-RESTaurant-API-Game git:(main) ✗ chmod +x ./start_app.sh
➜  Damn-Vulnerable-RESTaurant-API-Game git:(main) ✗ sudo ./start_app.sh
WARN[0000] /Users/adam/git/Damn-Vulnerable-RESTaurant-API-Game/docker-compose.yml: `version` is obsolete
[+] Running 1/0
 ✔ Container damn-vulnerable-restaurant-api-game-db-1  Creat...                                                      0.0s
Attaching to db-1, web-1
db-1   | chown: /var/lib/postgresql/data: Permission denied
db-1 exited with code 1
dependency failed to start: container damn-vulnerable-restaurant-api-game-db-1 exited (1)
```

this looks to be an issue with `postgres` and not necessarily this docker compose.. i think the script requires updating to run elevated privileges on postgres, see:

https://github.com/zalando/postgres-operator/issues/676

any assistance much appreciated, tyia!

**Comment by theowni** [comment]
Hi @GangGreenTemperTatum,
thanks for raising the issue.

Could you verify if the following `docker-compose.yml` works for you? Please, replace current content with the following content:
```
services:
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --workers 1 --reload"
    volumes:
      - ./app/:/app/
      - /app/.venv
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=restaurant
  db:
    image: postgres:15.4-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurant
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      start_period: 5s
    expose: 
      - 5432
```

**Comment by laucer** [comment]
I had the same issue and can confirm that cleaning `postgres_data` and changing `docker-compose.yml` file solved the problem.

**Comment by theowni** [comment]
I discussed this one with @laucer and he deleted `postgres_data` directory before launching the game with modified docker-compose. So, @GangGreenTemperTatum let's run the following commands and let me know what is the output:

```
docker compose down  # to tear down any running containers
sudo rm -rf postgres_data  # to remove directory with potentially "broken" permissions
# now, update the docker-compose if it's not updated
# and launch the app
./start_app.sh
```

**Comment by theowni** [comment]
Hi again @GangGreenTemperTatum,

I think I was able to reproduce the issue. The problem looks to be related with Colima. I used the following environment to reproduce the issue:
```
MacOS Sonoma 14.1
Colima version 0.6.8
Docker version 24.0.7
```

It looks like Colima doesn't have a proper permissions to your local directory to make changes in the directory. It's a kind of known issue which can be resolved in a non user-friendly way by modifying Colima configs. So, to make it more user-friendly, I modified `docker-compose.yml` to use named volumes instead of bind mounts. In this way, the database directory will be still persistent but in the directory managed by Docker (with proper permissions).

Here is the modified `docker-compose.yml`:
```
services:
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --workers 1 --reload"
    volumes:
      - ./app/:/app/
      - /app/.venv
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=restaurant
  db:
    image: postgres:15.4-alpine
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurant
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      start_period: 5s
    expose: 
      - 5432
volumes:
  pg_volume:
```

Update the `docker-compose.yml` content and run the commands:
```
docker compose down  # to tear down any running containers
sudo rm -rf postgres_data  # to remove the directory which won't be used anyway
./start_app.sh
```

I hope, it will resolve the issue!
